import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import './globals.css';
import QueryProvider from '@/providers/queryProvider';
import ReduxProvider from '@/providers/reduxProvider';
import AuthClientProvider from '@/providers/AuthClientProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <QueryProvider>
                    <ReduxProvider>
                        <AuthClientProvider />
                        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
                    </ReduxProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
